import type { PermissionKey } from "@/rbac/catalog";

export type RoleStatus = "active" | "inactive";
export type RoleKey = string;
export type RoleRecord = {
  id: string;
  key: string;
  name: string;
  description: string;
  permissions: PermissionKey[];
  userCount: number;
  isSystem: boolean;
  status: RoleStatus;
};
export type DemoRole = RoleRecord;

const allPermissions: PermissionKey[] = [
  "users.read",
  "users.create",
  "users.update",
  "users.delete",
  "roles.read",
  "roles.create",
  "roles.update",
  "roles.delete",
  "permissions.read",
  "ktx.access.read",
  "ktx.access.manage",
  "ktx.access.admin",
  "ktx.buildings.view",
  "ktx.buildings.create",
  "ktx.buildings.update",
  "ktx.buildings.deactivate",
  "ktx.floors.view",
  "ktx.floors.create",
  "ktx.floors.update",
  "ktx.floors.deactivate",
  "ktx.room_types.view",
  "ktx.room_types.create",
  "ktx.room_types.update",
  "ktx.room_types.deactivate",
  "ktx.rooms.view",
  "ktx.rooms.create",
  "ktx.rooms.update",
  "ktx.rooms.delete",
  "ktx.academic_years.view",
  "ktx.academic_years.create",
  "ktx.academic_years.update",
  "ktx.academic_years.deactivate",
  "ktx.students.view",
  "ktx.students.create",
  "ktx.students.update",
  "ktx.students.deactivate",
  "ktx.applications.view",
  "ktx.applications.create",
  "ktx.applications.update",
  "ktx.applications.submit",
  "ktx.applications.withdraw",
  "ktx.applications.review",
  "ktx.room_selection.view",
  "ktx.room_selection.select",
  "ktx.notifications.view",
  "ktx.notifications.create",
  "ktx.support.view",
  "ktx.support.create",
  "ktx.support.process",
  "ktx.support.comment",
  "ktx.contracts.view",
  "ktx.contracts.create",
  "ktx.contracts.update",
  "ktx.assignments.view",
  "ktx.assignments.create",
  "ktx.assignments.cancel",
  "ktx.residences.view",
  "ktx.residences.check_in",
  "ktx.residences.check_out",
  "ktx.residences.transfer",
  "ktx.residences.extend",
  "activity.read",
  "analytics.read",
  "ktx.invoices.view",
  "ktx.invoices.generate",
  "ktx.invoices.pay",
  "ktx.invoices.void",
  "ktx.debts.view",
  "ktx.payments.view",
  "ktx.payments.submit",
  "ktx.payments.verify",
  "ktx.payments.record",
  "ktx.payments.export",
  "ktx.reports.view",
  "ktx.reports.export",
  "settings.read",
  "settings.update",
  "profile.read",
  "profile.update",
];

export const demoRoles: DemoRole[] = [
  {
    id: "role-administrator",
    key: "administrator",
    name: "Administrator",
    description: "Toàn quyền quản trị không gian làm việc.",
    permissions: allPermissions,
    userCount: 1,
    isSystem: true,
    status: "active",
  },
  {
    id: "role-manager",
    key: "manager",
    name: "Manager",
    description: "Quản lý người dùng và hoạt động trong không gian làm việc.",
    permissions: [
      "users.read",
      "users.create",
      "users.update",
      "roles.read",
      "activity.read",
      "analytics.read",
      "settings.read",
      "profile.read",
    ],
    userCount: 2,
    isSystem: true,
    status: "active",
  },
  {
    id: "role-editor",
    key: "editor",
    name: "Editor",
    description: "Có thể cập nhật nội dung người dùng được phép truy cập.",
    permissions: [
      "users.read",
      "users.update",
      "roles.read",
      "activity.read",
      "analytics.read",
      "profile.read",
    ],
    userCount: 4,
    isSystem: true,
    status: "active",
  },
  {
    id: "role-viewer",
    key: "viewer",
    name: "Viewer",
    description: "Chỉ xem các khu vực được cấp quyền.",
    permissions: [
      "users.read",
      "roles.read",
      "activity.read",
      "analytics.read",
      "profile.read",
    ],
    userCount: 7,
    isSystem: true,
    status: "active",
  },
];
