export const permissionCatalog = [
  {
    key: "users.read",
    label: "Xem người dùng",
    resource: "users",
    resourceLabel: "Người dùng",
    description: "Xem danh sách và thông tin chi tiết người dùng.",
  },
  {
    key: "users.create",
    label: "Mời người dùng",
    resource: "users",
    resourceLabel: "Người dùng",
    description: "Tạo lời mời người dùng mới trong không gian làm việc.",
  },
  {
    key: "users.update",
    label: "Cập nhật người dùng",
    resource: "users",
    resourceLabel: "Người dùng",
    description: "Chỉnh sửa hồ sơ, vai trò và trạng thái người dùng.",
  },
  {
    key: "users.delete",
    label: "Xóa người dùng",
    resource: "users",
    resourceLabel: "Người dùng",
    description: "Xóa người dùng khỏi không gian làm việc.",
  },
  {
    key: "roles.read",
    label: "Xem vai trò",
    resource: "roles",
    resourceLabel: "Vai trò",
    description: "Xem vai trò và các quyền được gán.",
  },
  {
    key: "roles.create",
    label: "Tạo vai trò",
    resource: "roles",
    resourceLabel: "Vai trò",
    description: "Tạo vai trò tùy chỉnh mới.",
  },
  {
    key: "roles.update",
    label: "Cập nhật vai trò",
    resource: "roles",
    resourceLabel: "Vai trò",
    description: "Chỉnh sửa thông tin và quyền của vai trò.",
  },
  {
    key: "roles.delete",
    label: "Xóa vai trò",
    resource: "roles",
    resourceLabel: "Vai trò",
    description: "Xóa vai trò tùy chỉnh chưa được gán cho người dùng.",
  },
  {
    key: "permissions.read",
    label: "Xem quyền hạn",
    resource: "permissions",
    resourceLabel: "Quyền hạn",
    description: "Xem danh mục quyền RBAC dùng trong hệ thống.",
  },
  {
    key: "ktx.access.read",
    label: "Truy cập dữ liệu KTX",
    resource: "application",
    resourceLabel: "QNU KTX",
    description: "Truy cập các dữ liệu KTX được cấp phép xem.",
  },
  {
    key: "ktx.access.manage",
    label: "Quản lý nghiệp vụ KTX",
    resource: "application",
    resourceLabel: "QNU KTX",
    description: "Thực hiện các nghiệp vụ quản lý KTX.",
  },
  {
    key: "ktx.access.admin",
    label: "Quản trị toàn bộ KTX",
    resource: "application",
    resourceLabel: "QNU KTX",
    description: "Toàn quyền quản trị các phân hệ KTX.",
  },
  {
    key: "ktx.buildings.view",
    label: "Xem tòa nhà",
    resource: "buildings",
    resourceLabel: "Tòa nhà",
    description: "Xem danh sách và thông tin chi tiết tòa nhà.",
  },
  {
    key: "ktx.buildings.create",
    label: "Tạo tòa nhà",
    resource: "buildings",
    resourceLabel: "Tòa nhà",
    description: "Tạo tòa nhà mới trong danh mục ký túc xá.",
  },
  {
    key: "ktx.buildings.update",
    label: "Cập nhật tòa nhà",
    resource: "buildings",
    resourceLabel: "Tòa nhà",
    description: "Chỉnh sửa thông tin tòa nhà.",
  },
  {
    key: "ktx.buildings.deactivate",
    label: "Ngừng sử dụng tòa nhà",
    resource: "buildings",
    resourceLabel: "Tòa nhà",
    description: "Ngừng sử dụng tòa nhà không có tầng hoặc phòng.",
  },
  {
    key: "ktx.floors.view",
    label: "Xem tầng",
    resource: "floors",
    resourceLabel: "Tầng",
    description: "Xem các tầng thuộc tòa nhà.",
  },
  {
    key: "ktx.floors.create",
    label: "Tạo tầng",
    resource: "floors",
    resourceLabel: "Tầng",
    description: "Tạo tầng mới trong tòa nhà.",
  },
  {
    key: "ktx.floors.update",
    label: "Cập nhật tầng",
    resource: "floors",
    resourceLabel: "Tầng",
    description: "Chỉnh sửa thông tin tầng.",
  },
  {
    key: "ktx.floors.deactivate",
    label: "Ngừng sử dụng tầng",
    resource: "floors",
    resourceLabel: "Tầng",
    description: "Ngừng sử dụng tầng không có phòng hoạt động.",
  },
  {
    key: "ktx.room_types.view",
    label: "Xem loại phòng",
    resource: "roomTypes",
    resourceLabel: "Loại phòng",
    description: "Xem danh mục loại phòng.",
  },
  {
    key: "ktx.room_types.create",
    label: "Tạo loại phòng",
    resource: "roomTypes",
    resourceLabel: "Loại phòng",
    description: "Tạo loại phòng mới.",
  },
  {
    key: "ktx.room_types.update",
    label: "Cập nhật loại phòng",
    resource: "roomTypes",
    resourceLabel: "Loại phòng",
    description: "Chỉnh sửa thông tin loại phòng.",
  },
  {
    key: "ktx.room_types.deactivate",
    label: "Ngừng sử dụng loại phòng",
    resource: "roomTypes",
    resourceLabel: "Loại phòng",
    description: "Ngừng sử dụng loại phòng không có phòng đang tham chiếu.",
  },
  {
    key: "ktx.rooms.view",
    label: "Xem phòng",
    resource: "rooms",
    resourceLabel: "Phòng",
    description: "Xem danh sách và chi tiết phòng.",
  },
  {
    key: "ktx.rooms.create",
    label: "Tạo phòng",
    resource: "rooms",
    resourceLabel: "Phòng",
    description: "Tạo phòng mới trong tòa nhà và tầng.",
  },
  {
    key: "ktx.rooms.update",
    label: "Cập nhật phòng",
    resource: "rooms",
    resourceLabel: "Phòng",
    description: "Chỉnh sửa thông tin phòng.",
  },
  {
    key: "ktx.rooms.delete",
    label: "Ngừng sử dụng phòng",
    resource: "rooms",
    resourceLabel: "Phòng",
    description: "Ngừng sử dụng phòng.",
  },
  {
    key: "ktx.academic_years.view",
    label: "Xem năm học",
    resource: "academicYears",
    resourceLabel: "Năm học",
    description: "Xem danh sách và chi tiết năm học.",
  },
  {
    key: "ktx.registration_periods.view",
    label: "Xem đợt đăng ký",
    resource: "registrationPeriods",
    resourceLabel: "Đợt đăng ký",
    description: "Xem các đợt đăng ký KTX.",
  },
  {
    key: "ktx.priority_objects.view",
    label: "Xem đối tượng ưu tiên",
    resource: "priorityObjects",
    resourceLabel: "Đối tượng ưu tiên",
    description:
      "Xem các nhóm đối tượng và điểm ưu tiên dùng khi xét duyệt hồ sơ.",
  },
  {
    key: "ktx.priority_objects.create",
    label: "Tạo đối tượng ưu tiên",
    resource: "priorityObjects",
    resourceLabel: "Đối tượng ưu tiên",
    description: "Tạo nhóm đối tượng ưu tiên mới.",
  },
  {
    key: "ktx.priority_objects.update",
    label: "Cập nhật đối tượng ưu tiên",
    resource: "priorityObjects",
    resourceLabel: "Đối tượng ưu tiên",
    description: "Chỉnh sửa tên, điểm và trạng thái đối tượng ưu tiên.",
  },
  {
    key: "ktx.priority_objects.deactivate",
    label: "Ngừng đối tượng ưu tiên",
    resource: "priorityObjects",
    resourceLabel: "Đối tượng ưu tiên",
    description: "Ngừng sử dụng đối tượng ưu tiên khi không còn áp dụng.",
  },
  {
    key: "ktx.priority_objects.areas.manage",
    label: "Quản lý địa bàn đối tượng ưu tiên",
    resource: "priorityObjects",
    resourceLabel: "Đối tượng ưu tiên",
    description:
      "Thêm, ngừng hoặc xóa địa bàn hành chính đủ điều kiện cho đối tượng ưu tiên.",
  },
  {
    key: "ktx.registration_periods.create",
    label: "Tạo đợt đăng ký",
    resource: "registrationPeriods",
    resourceLabel: "Đợt đăng ký",
    description: "Tạo một đợt đăng ký mới.",
  },
  {
    key: "ktx.registration_periods.update",
    label: "Cập nhật đợt đăng ký",
    resource: "registrationPeriods",
    resourceLabel: "Đợt đăng ký",
    description: "Chỉnh sửa đợt đăng ký khi còn nháp.",
  },
  {
    key: "ktx.registration_periods.open",
    label: "Mở đợt đăng ký",
    resource: "registrationPeriods",
    resourceLabel: "Đợt đăng ký",
    description: "Mở cửa tiếp nhận hồ sơ.",
  },
  {
    key: "ktx.registration_periods.close",
    label: "Đóng đợt đăng ký",
    resource: "registrationPeriods",
    resourceLabel: "Đợt đăng ký",
    description: "Dừng tiếp nhận hồ sơ.",
  },
  {
    key: "ktx.registration_periods.archive",
    label: "Lưu trữ đợt đăng ký",
    resource: "registrationPeriods",
    resourceLabel: "Đợt đăng ký",
    description: "Lưu trữ đợt đã kết thúc.",
  },
  {
    key: "ktx.registration_periods.deactivate",
    label: "Ngừng đợt đăng ký",
    resource: "registrationPeriods",
    resourceLabel: "Đợt đăng ký",
    description: "Ngừng đợt đã xử lý.",
  },
  {
    key: "ktx.academic_years.create",
    label: "Tạo năm học",
    resource: "academicYears",
    resourceLabel: "Năm học",
    description: "Tạo năm học mới.",
  },
  {
    key: "ktx.academic_years.update",
    label: "Cập nhật năm học",
    resource: "academicYears",
    resourceLabel: "Năm học",
    description: "Chỉnh sửa thông tin và trạng thái năm học.",
  },
  {
    key: "ktx.academic_years.deactivate",
    label: "Ngừng năm học",
    resource: "academicYears",
    resourceLabel: "Năm học",
    description: "Ngừng năm học khi không còn kỳ đăng ký mở.",
  },
  {
    key: "ktx.students.view",
    label: "Xem sinh viên",
    resource: "students",
    resourceLabel: "Sinh viên",
    description: "Xem danh sách và hồ sơ sinh viên.",
  },
  {
    key: "ktx.students.create",
    label: "Tạo sinh viên",
    resource: "students",
    resourceLabel: "Sinh viên",
    description: "Tạo hồ sơ sinh viên mới.",
  },
  {
    key: "ktx.students.update",
    label: "Cập nhật sinh viên",
    resource: "students",
    resourceLabel: "Sinh viên",
    description: "Chỉnh sửa thông tin và trạng thái sinh viên.",
  },
  {
    key: "ktx.students.deactivate",
    label: "Ngừng hồ sơ sinh viên",
    resource: "students",
    resourceLabel: "Sinh viên",
    description: "Ngừng sử dụng hồ sơ sinh viên.",
  },
  {
    key: "ktx.applications.view",
    label: "Xem hồ sơ đăng ký",
    resource: "applications",
    resourceLabel: "Hồ sơ đăng ký",
    description: "Xem và tra cứu hồ sơ đăng ký nội trú.",
  },
  {
    key: "ktx.applications.create",
    label: "Tạo hồ sơ đăng ký",
    resource: "applications",
    resourceLabel: "Hồ sơ đăng ký",
    description: "Tạo mới hồ sơ đăng ký KTX cho sinh viên.",
  },
  {
    key: "ktx.applications.update",
    label: "Chỉnh sửa hồ sơ đăng ký",
    resource: "applications",
    resourceLabel: "Hồ sơ đăng ký",
    description:
      "Chỉnh sửa thông tin sinh viên, nguyện vọng và diện ưu tiên của hồ sơ.",
  },
  {
    key: "ktx.applications.submit",
    label: "Nộp hồ sơ đăng ký",
    resource: "applications",
    resourceLabel: "Hồ sơ đăng ký",
    description: "Lưu nháp và nộp hồ sơ đăng ký KTX.",
  },
  {
    key: "ktx.applications.withdraw",
    label: "Rút hồ sơ đăng ký",
    resource: "applications",
    resourceLabel: "Hồ sơ đăng ký",
    description: "Rút hồ sơ khi đợt đăng ký còn hiệu lực.",
  },
  {
    key: "ktx.applications.review",
    label: "Duyệt hồ sơ đăng ký",
    resource: "applications",
    resourceLabel: "Hồ sơ đăng ký",
    description: "Phê duyệt, từ chối hoặc yêu cầu bổ sung hồ sơ.",
  },
  {
    key: "ktx.room_selection.view",
    label: "Xem lựa chọn phòng",
    resource: "roomSelection",
    resourceLabel: "Lựa chọn phòng",
    description: "Xem phòng có thể chọn trong đợt.",
  },
  {
    key: "ktx.room_selection.select",
    label: "Chọn hoặc đổi phòng",
    resource: "roomSelection",
    resourceLabel: "Lựa chọn phòng",
    description: "Chọn hoặc thay đổi phòng trong thời gian đợt cho phép.",
  },
  {
    key: "ktx.notifications.view",
    label: "Xem thông báo",
    resource: "notifications",
    resourceLabel: "Thông báo",
    description: "Xem danh sách và chi tiết thông báo đã gửi.",
  },
  {
    key: "ktx.notifications.create",
    label: "Tạo thông báo",
    resource: "notifications",
    resourceLabel: "Thông báo",
    description: "Gửi thông báo đến sinh viên hoặc tài khoản.",
  },
  {
    key: "ktx.support.view",
    label: "Xem yêu cầu hỗ trợ",
    resource: "support",
    resourceLabel: "Hỗ trợ",
    description: "Xem danh sách và chi tiết yêu cầu hỗ trợ.",
  },
  {
    key: "ktx.support.create",
    label: "Tạo yêu cầu hỗ trợ",
    resource: "support",
    resourceLabel: "Hỗ trợ",
    description: "Tạo yêu cầu hỗ trợ mới.",
  },
  {
    key: "ktx.support.process",
    label: "Xử lý yêu cầu",
    resource: "support",
    resourceLabel: "Hỗ trợ",
    description: "Cập nhật trạng thái và ghi chú xử lý.",
  },
  {
    key: "ktx.support.comment",
    label: "Bình luận yêu cầu",
    resource: "support",
    resourceLabel: "Hỗ trợ",
    description: "Thêm trao đổi vào yêu cầu hỗ trợ.",
  },
  {
    key: "ktx.contracts.view",
    label: "Xem hợp đồng nội trú",
    resource: "contracts",
    resourceLabel: "Hợp đồng",
    description: "Xem hợp đồng và trạng thái hợp đồng nội trú.",
  },
  {
    key: "ktx.contracts.create",
    label: "Tạo hợp đồng nội trú",
    resource: "contracts",
    resourceLabel: "Hợp đồng",
    description: "Tạo hoặc gửi hợp đồng nội trú cho sinh viên.",
  },
  {
    key: "ktx.contracts.update",
    label: "Cập nhật hợp đồng nội trú",
    resource: "contracts",
    resourceLabel: "Hợp đồng",
    description: "Cập nhật, kích hoạt hoặc hủy hợp đồng nội trú.",
  },
  {
    key: "activity.read",
    label: "Xem hoạt động",
    resource: "activity",
    resourceLabel: "Hoạt động",
    description: "Xem nhật ký hoạt động trong không gian làm việc.",
  },
  {
    key: "ktx.assignments.view",
    label: "Xem xếp phòng",
    resource: "assignments",
    resourceLabel: "Xếp phòng",
    description: "Xem các phân phòng và hồ sơ đủ điều kiện.",
  },
  {
    key: "ktx.assignments.create",
    label: "Xếp sinh viên vào phòng",
    resource: "assignments",
    resourceLabel: "Xếp phòng",
    description: "Gán hồ sơ đã duyệt vào phòng còn chỗ.",
  },
  {
    key: "ktx.assignments.cancel",
    label: "Hủy xếp phòng",
    resource: "assignments",
    resourceLabel: "Xếp phòng",
    description: "Hủy phân phòng và cập nhật số chỗ trống.",
  },
  {
    key: "ktx.residences.view",
    label: "Xem cư trú",
    resource: "residences",
    resourceLabel: "Cư trú",
    description: "Xem các lượt cư trú và lịch sử vận hành.",
  },
  {
    key: "ktx.residences.check_in",
    label: "Nhận phòng",
    resource: "residences",
    resourceLabel: "Cư trú",
    description: "Xác nhận sinh viên nhận phòng từ phân phòng.",
  },
  {
    key: "ktx.residences.check_out",
    label: "Trả phòng",
    resource: "residences",
    resourceLabel: "Cư trú",
    description: "Kết thúc lượt cư trú và cập nhật số chỗ trống.",
  },
  {
    key: "ktx.residences.transfer",
    label: "Chuyển phòng",
    resource: "residences",
    resourceLabel: "Cư trú",
    description: "Chuyển sinh viên sang phòng mới còn chỗ.",
  },
  {
    key: "ktx.residences.extend",
    label: "Gia hạn cư trú",
    resource: "residences",
    resourceLabel: "Cư trú",
    description: "Cập nhật ngày kết thúc dự kiến của lượt cư trú.",
  },
  {
    key: "ktx.invoices.view",
    label: "Xem hóa đơn",
    resource: "invoices",
    resourceLabel: "Hóa đơn",
    description: "Xem hóa đơn và thông tin công nợ của sinh viên.",
  },
  {
    key: "ktx.invoices.generate",
    label: "Tạo hóa đơn",
    resource: "invoices",
    resourceLabel: "Hóa đơn",
    description: "Tạo hóa đơn đơn lẻ hoặc theo đợt.",
  },
  {
    key: "ktx.invoices.pay",
    label: "Ghi nhận thanh toán",
    resource: "invoices",
    resourceLabel: "Hóa đơn",
    description: "Ghi nhận khoản thanh toán cho hóa đơn.",
  },
  {
    key: "ktx.invoices.void",
    label: "Hủy thanh toán",
    resource: "invoices",
    resourceLabel: "Hóa đơn",
    description: "Hủy mềm một khoản thanh toán đã ghi nhận.",
  },
  {
    key: "ktx.debts.view",
    label: "Xem công nợ",
    resource: "debts",
    resourceLabel: "Công nợ",
    description: "Xem tổng hợp công nợ theo sinh viên.",
  },
  {
    key: "ktx.payments.view",
    label: "Xem hồ sơ thanh toán",
    resource: "payments",
    resourceLabel: "Thanh toán KTX",
    description: "Xem hóa đơn và các hồ sơ nộp thanh toán KTX.",
  },
  {
    key: "ktx.payments.submit",
    label: "Nộp biên lai thanh toán",
    resource: "payments",
    resourceLabel: "Thanh toán KTX",
    description: "Nộp ảnh biên lai thanh toán cho hóa đơn của mình.",
  },
  {
    key: "ktx.payments.verify",
    label: "Xác minh thanh toán",
    resource: "payments",
    resourceLabel: "Thanh toán KTX",
    description: "Kiểm tra và xác minh hoặc từ chối biên lai sinh viên đã nộp.",
  },
  {
    key: "ktx.payments.record",
    label: "Ghi nhận thanh toán",
    resource: "payments",
    resourceLabel: "Thanh toán KTX",
    description: "Ghi nhận khoản thanh toán được thực hiện ngoài hệ thống.",
  },
  {
    key: "ktx.payments.export",
    label: "Xuất dữ liệu thanh toán",
    resource: "payments",
    resourceLabel: "Thanh toán KTX",
    description: "Xuất danh sách và kết quả đối soát thanh toán.",
  },
  {
    key: "ktx.reports.view",
    label: "Xem báo cáo KTX",
    resource: "reports",
    resourceLabel: "Báo cáo KTX",
    description: "Xem các chỉ số vận hành, hồ sơ, phòng và doanh thu.",
  },
  {
    key: "ktx.reports.export",
    label: "Xuất báo cáo KTX",
    resource: "reports",
    resourceLabel: "Báo cáo KTX",
    description: "Xuất dữ liệu báo cáo theo quyền được cấp.",
  },
  {
    key: "analytics.read",
    label: "Xem phân tích",
    resource: "analytics",
    resourceLabel: "Phân tích",
    description: "Xem các báo cáo và số liệu phân tích.",
  },
  {
    key: "settings.read",
    label: "Xem cài đặt",
    resource: "settings",
    resourceLabel: "Cài đặt",
    description: "Xem các thiết lập của không gian làm việc.",
  },
  {
    key: "settings.update",
    label: "Cập nhật cài đặt",
    resource: "settings",
    resourceLabel: "Cài đặt",
    description: "Thay đổi các thiết lập của không gian làm việc.",
  },
  {
    key: "profile.read",
    label: "Xem hồ sơ",
    resource: "profile",
    resourceLabel: "Hồ sơ",
    description: "Xem hồ sơ của tài khoản đang đăng nhập.",
  },
  {
    key: "profile.update",
    label: "Cập nhật hồ sơ",
    resource: "profile",
    resourceLabel: "Hồ sơ",
    description: "Cập nhật thông tin cá nhân và tùy chọn hồ sơ.",
  },
  {
    key: "ktx.fee_rates.view",
    label: "Xem mức phí",
    resource: "feeRates",
    resourceLabel: "Mức phí",
    description: "Xem bảng giá theo loại phòng và phòng.",
  },
  {
    key: "ktx.fee_rates.create",
    label: "Tạo mức phí",
    resource: "feeRates",
    resourceLabel: "Mức phí",
    description: "Tạo mức phí theo năm học, loại phòng hoặc theo phòng.",
  },
  {
    key: "ktx.fee_rates.update",
    label: "Cập nhật mức phí",
    resource: "feeRates",
    resourceLabel: "Mức phí",
    description: "Cập nhật số tiền và thời gian hiệu lực.",
  },
  {
    key: "ktx.fee_rates.deactivate",
    label: "Ngừng mức phí",
    resource: "feeRates",
    resourceLabel: "Mức phí",
    description: "Ngừng áp dụng mức phí chưa được tham chiếu bởi hóa đơn.",
  },
] as const;

export type PermissionKey = (typeof permissionCatalog)[number]["key"];
export type PermissionCatalogItem = (typeof permissionCatalog)[number];
