import type { User } from "@/features/users/types";
export const users: User[] = [
  {
    id: "u1",
    name: "Alex Morgan",
    email: "alex.morgan@example.com",
    role: "Administrator",
    status: "active",
    createdAt: "2025-08-01",
  },
  {
    id: "u2",
    name: "Avery Davis",
    email: "avery.davis@example.com",
    role: "Editor",
    status: "active",
    createdAt: "2025-03-19",
  },
  {
    id: "u3",
    name: "Cameron Ellis",
    email: "cameron.ellis@example.com",
    role: "Viewer",
    status: "active",
    createdAt: "2025-03-04",
  },
  {
    id: "u4",
    name: "Casey Brooks",
    email: "casey.brooks@example.com",
    role: "Viewer",
    status: "inactive",
    createdAt: "2025-05-14",
  },
  {
    id: "u5",
    name: "Drew Parker",
    email: "drew.parker@example.com",
    role: "Manager",
    status: "inactive",
    createdAt: "2025-02-16",
  },
  {
    id: "u6",
    name: "Jamie Wilson",
    email: "jamie.wilson@example.com",
    role: "Viewer",
    status: "suspended",
    createdAt: "2025-04-08",
  },
  {
    id: "u7",
    name: "Jordan Lee",
    email: "jordan.lee@example.com",
    role: "Editor",
    status: "active",
    createdAt: "2025-06-24",
  },
  {
    id: "u8",
    name: "Morgan Chen",
    email: "morgan.chen@example.com",
    role: "Viewer",
    status: "pending",
    createdAt: "2025-06-12",
  },
  {
    id: "u9",
    name: "Quinn Baker",
    email: "quinn.baker@example.com",
    role: "Viewer",
    status: "pending",
    createdAt: "2025-01-27",
  },
  {
    id: "u10",
    name: "Reese Carter",
    email: "reese.carter@example.com",
    role: "Editor",
    status: "active",
    createdAt: "2024-12-11",
  },
  {
    id: "u11",
    name: "Taylor Reed",
    email: "taylor.reed@example.com",
    role: "Manager",
    status: "active",
    createdAt: "2025-07-02",
  },
  {
    id: "u12",
    name: "Riley Adams",
    email: "riley.adams@example.com",
    role: "Viewer",
    status: "inactive",
    createdAt: "2025-07-09",
  },
  {
    id: "u13",
    name: "Emerson Gray",
    email: "emerson.gray@example.com",
    role: "Editor",
    status: "active",
    createdAt: "2025-07-14",
  },
  {
    id: "u14",
    name: "Hayden Scott",
    email: "hayden.scott@example.com",
    role: "Viewer",
    status: "pending",
    createdAt: "2025-07-21",
  },
];

export async function loadUsers() {
  return users;
}
