"""Base Workflow Node Abstraction & Execution Context."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from app.modules.workflows.schemas import WorkflowNodeSpec


@dataclass
class WorkflowContext:
    """Shared state passed between nodes during DAG execution."""

    workflow_id: str
    tenant_id: str
    conversation_id: str | None
    inputs: dict[str, Any]
    outputs: dict[str, Any] = field(default_factory=dict)
    node_data: dict[str, Any] = field(default_factory=dict)
    db: AsyncSession | None = None


@dataclass
class NodeExecutionResult:
    """Output generated by a single node."""

    node_id: str
    status: str = "completed"  # completed, failed, paused_for_approval
    output: dict[str, Any] = field(default_factory=dict)
    next_node_override: str | None = None
    error: str | None = None


class BaseNodeHandler(ABC):
    """Strategy interface for executing a specific DAG node type."""

    @abstractmethod
    async def execute(
        self, node_spec: WorkflowNodeSpec, context: WorkflowContext
    ) -> NodeExecutionResult:
        """Run node logic and return structured result."""
        ...
