"""Base Workflow Node Abstraction & Execution Context."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from app.modules.assistants.schemas import AssistantRuntimeProfile
from app.modules.workflows.schemas import WorkflowNodeSpec


@dataclass
class WorkflowContext:
    """Shared state passed between nodes during DAG execution."""

    workflow_id: str
    tenant_id: str
    conversation_id: str | None
    inputs: dict[str, Any]
    outputs: dict[str, Any] = field(default_factory=dict)
    node_data: dict[str, Any] = field(default_factory=dict)
    db: AsyncSession | None = None
    assistant_profile: AssistantRuntimeProfile | None = None
    correlation_id: str | None = None
    execution_id: str | None = None
    node_traces: list[NodeExecutionTrace] = field(default_factory=list)


@dataclass
class NodeExecutionTrace:
    """Structured trace captured by the engine and persisted after the run ends."""

    node_id: str
    node_type: str
    status: str
    input_data: dict[str, Any]
    output_data: dict[str, Any]
    latency_ms: float


@dataclass
class NodeExecutionResult:
    """Output generated by a single node."""

    node_id: str
    status: str = "completed"  # completed, failed, paused_for_approval
    output: dict[str, Any] = field(default_factory=dict)
    next_node_override: str | None = None
    selected_port: str | None = None
    error: str | None = None


class BaseNodeHandler(ABC):
    """Strategy interface for executing a specific DAG node type."""

    @abstractmethod
    async def execute(
        self, node_spec: WorkflowNodeSpec, context: WorkflowContext
    ) -> NodeExecutionResult:
        """Run node logic and return structured result."""
        ...
