import type { ActivityEvent } from "@/features/activity/types";

export const activityEvents: ActivityEvent[] = [
  {
    id: "activity-1",
    type: "user.updated",
    resource: "users",
    actor: "Olivia Rhye",
    actorInitials: "OR",
    action: "đã cập nhật",
    subject: "Alex Morgan",
    createdAt: "2026-08-09T09:42:00+07:00",
    metadata: {
      "Trường thay đổi": "Vai trò, trạng thái",
      "Vai trò mới": "Administrator",
    },
  },
  {
    id: "activity-2",
    type: "role.created",
    resource: "roles",
    actor: "Administrator",
    actorInitials: "AD",
    action: "đã tạo vai trò",
    subject: "Content Reviewer",
    createdAt: "2026-08-09T08:30:00+07:00",
    metadata: { "Role key": "content_reviewer", "Quyền hạn": "5" },
  },
  {
    id: "activity-3",
    type: "settings.updated",
    resource: "settings",
    actor: "Olivia Rhye",
    actorInitials: "OR",
    action: "đã cập nhật",
    subject: "tùy chọn thông báo",
    createdAt: "2026-08-08T16:20:00+07:00",
    metadata: { Nhóm: "Tài khoản", "Thay đổi": "Cảnh báo bảo mật" },
  },
  {
    id: "activity-4",
    type: "user.created",
    resource: "users",
    actor: "Avery Davis",
    actorInitials: "AD",
    action: "đã mời",
    subject: "maya.chen@example.com",
    createdAt: "2026-08-08T13:10:00+07:00",
    metadata: { "Vai trò": "Editor", "Trạng thái": "Đang chờ" },
  },
  {
    id: "activity-5",
    type: "security.changed",
    resource: "security",
    actor: "Olivia Rhye",
    actorInitials: "OR",
    action: "đã thay đổi",
    subject: "cài đặt bảo mật",
    createdAt: "2026-08-07T10:05:00+07:00",
    metadata: {
      "Thiết lập": "Phiên đăng nhập",
      "Kết quả": "Đăng xuất phiên khác",
    },
  },
  {
    id: "activity-6",
    type: "role.updated",
    resource: "roles",
    actor: "Administrator",
    actorInitials: "AD",
    action: "đã cập nhật quyền của",
    subject: "Manager",
    createdAt: "2026-08-06T15:45:00+07:00",
    metadata: { "Quyền thêm": "roles.update", "Quyền bỏ": "settings.update" },
  },
  {
    id: "activity-7",
    type: "user.deleted",
    resource: "users",
    actor: "Olivia Rhye",
    actorInitials: "OR",
    action: "đã xóa",
    subject: "Taylor Reed",
    createdAt: "2026-08-03T11:15:00+07:00",
    metadata: { "Lý do": "Tài khoản không còn hoạt động" },
  },
];
