import type { UisMajorInfo } from "@/types/domain-templates";

export const UIS_MAJORS_DATABASE: UisMajorInfo[] = [
  {
    major_code: "7480201",
    major_name: "Công nghệ Thông tin",
    faculty: "Khoa Công nghệ Thông tin",
    degree: "Kỹ sư / Cử nhân (4.5 năm)",
    quota_2025: 220,
    benchmark_2024: 24.5,
    benchmark_2023: 23.5,
    benchmark_2022: 23.0,
    combinations: ["A00", "A01", "D01", "D07"],
    tuition_per_credit_vnd: 450000,
    tuition_per_year_vnd: 16500000,
    career_opportunities: [
      "Kỹ sư Phát triển Phần mềm (Fullstack, Mobile, Cloud)",
      "Chuyên viên Phân tích Hệ thống và Cơ sở Dữ liệu",
      "Kỹ sư Vận hành AI và Trí tuệ Nhân tạo",
    ],
  },
  {
    major_code: "7480103",
    major_name: "Kỹ thuật Phần mềm",
    faculty: "Khoa Công nghệ Thông tin",
    degree: "Kỹ sư (4.5 năm)",
    quota_2025: 140,
    benchmark_2024: 23.0,
    benchmark_2023: 22.0,
    benchmark_2022: 21.5,
    combinations: ["A00", "A01", "D01"],
    tuition_per_credit_vnd: 450000,
    tuition_per_year_vnd: 16500000,
    career_opportunities: [
      "Kiến trúc sư Phần mềm Doanh nghiệp (Enterprise Architect)",
      "Kiểm thử tự động & Đảm bảo chất lượng (QA/QC Engineer)",
      "Quản trị Dự án Agile / Scrum Master",
    ],
  },
  {
    major_code: "7480107",
    major_name: "Trí tuệ Nhân tạo & Khoa học Dữ liệu",
    faculty: "Khoa Công nghệ Thông tin & Khoa Toán - Thống kê",
    degree: "Cử nhân Chất lượng Cao (4 năm)",
    quota_2025: 80,
    benchmark_2024: 24.0,
    benchmark_2023: 23.0,
    benchmark_2022: 22.5,
    combinations: ["A00", "A01", "D07"],
    tuition_per_credit_vnd: 520000,
    tuition_per_year_vnd: 18500000,
    career_opportunities: [
      "Kỹ sư Học máy & Học sâu (Machine Learning / Deep Learning)",
      "Chuyên gia Khoa học Dữ liệu (Data Scientist)",
      "Chuyên viên Tinh chỉnh Mô hình AI & RAG Engineer",
    ],
  },
  {
    major_code: "7140209",
    major_name: "Sư phạm Toán học",
    faculty: "Khoa Toán - Thống kê",
    degree: "Cử nhân Sư phạm (4 năm, Miễn 100% học phí & Trợ cấp theo NĐ 116)",
    quota_2025: 100,
    benchmark_2024: 26.5,
    benchmark_2023: 25.5,
    benchmark_2022: 25.0,
    combinations: ["A00", "A01", "D07"],
    tuition_per_credit_vnd: 0,
    tuition_per_year_vnd: 0,
    career_opportunities: [
      "Giáo viên môn Toán tại các Trường THPT chuyên và chuẩn quốc gia",
      "Giảng viên Toán học tại các trường Đại học, Cao đẳng",
      "Chuyên viên Nghiên cứu và Phát triển Chương trình Đào tạo",
    ],
  },
  {
    major_code: "7220201",
    major_name: "Ngôn ngữ Anh",
    faculty: "Khoa Ngoại ngữ",
    degree: "Cử nhân (4 năm)",
    quota_2025: 180,
    benchmark_2024: 22.5,
    benchmark_2023: 21.5,
    benchmark_2022: 21.0,
    combinations: ["D01", "A01", "D14", "D15"],
    tuition_per_credit_vnd: 410000,
    tuition_per_year_vnd: 15000000,
    career_opportunities: [
      "Biên - Phiên dịch viên cao cấp tại các tập đoàn đa quốc gia",
      "Chuyên viên Đối ngoại và Hợp tác Quốc tế",
      "Giáo viên và Chuyên gia Đào tạo Tiếng Anh học thuật (IELTS/TOEIC)",
    ],
  },
  {
    major_code: "7340101",
    major_name: "Quản trị Kinh doanh",
    faculty: "Khoa Kinh tế & Kế toán",
    degree: "Cử nhân (4 năm)",
    quota_2025: 200,
    benchmark_2024: 21.0,
    benchmark_2023: 20.5,
    benchmark_2022: 20.0,
    combinations: ["A00", "A01", "D01", "D07"],
    tuition_per_credit_vnd: 410000,
    tuition_per_year_vnd: 15000000,
    career_opportunities: [
      "Chuyên viên Quản trị Chiến lược và Vận hành Doanh nghiệp",
      "Chuyên viên Marketing & Phát triển Thị trường",
      "Khởi nghiệp và Điều hành Doanh nghiệp Vừa và Nhỏ",
    ],
  },
];
