"""Data Quality Gate — Automated Integrity Verification & Blocking Issue Detection.

Enforces pre-publish quality criteria specified in the QNU AI Platform Knowledge Normalization Plan:
- EncodingValidator: 0 replacement characters (U+FFFD), 0 mojibake.
- DuplicateContentValidator: Table text duplication ratio < 1%.
- TableShapeValidator: Column count parity across rows, no orphan columns.
- BusinessKeyValidator: Valid 7-digit Ministry program codes, unique task codes.
- CrossTableConflictValidator: Detects conflicting values (e.g. AI program code 7480107 vs 7480207)
  and marks document as 'blocking', routing to review_pending for human verification.
"""

from __future__ import annotations

import re
from datetime import UTC, datetime

from pydantic import BaseModel, Field

from app.modules.knowledge.normalization.models import (
    CanonicalDocument,
    CanonicalTable,
    QualityIssue,
)


class DocumentQualityReport(BaseModel):
    """Evaluation report generated by DataQualityGate."""

    document_id: str
    quality_score: float = Field(ge=0.0, le=1.0)
    issues: list[QualityIssue] = Field(default_factory=list)
    passed: bool = Field(description="True if no blocking issues were detected")
    checked_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class DataQualityGate:
    """Automated validator suite preventing hallucination-inducing or corrupted data from entering RAG."""

    def evaluate(self, doc: CanonicalDocument) -> DocumentQualityReport:
        issues: list[QualityIssue] = []

        # 1. Encoding check
        issues.extend(self._check_encoding(doc))

        # 2. Table duplication check
        issues.extend(self._check_duplicate_content(doc))

        # 3. Table shape check
        issues.extend(self._check_table_shape(doc))

        # 4. Table header and business-key integrity checks
        issues.extend(self._check_table_headers(doc))
        issues.extend(self._check_duplicate_business_keys(doc))

        # 5. Cross-table conflict check
        issues.extend(self._check_cross_table_conflicts(doc))

        # Calculate quality score
        blocking_count = sum(1 for iss in issues if iss.severity == "blocking")
        warning_count = sum(1 for iss in issues if iss.severity == "warning")

        # Base score 1.0, deduct for warnings, 0.0 if blocking issues exist
        score = max(0.0, 1.0 - (warning_count * 0.05))
        if blocking_count > 0:
            score = min(score, 0.50)

        passed = (blocking_count == 0)

        return DocumentQualityReport(
            document_id=doc.document_id,
            quality_score=round(score, 2),
            issues=issues,
            passed=passed,
        )

    def _check_encoding(self, doc: CanonicalDocument) -> list[QualityIssue]:
        issues: list[QualityIssue] = []
        for b in doc.blocks:
            if "\ufffd" in b.text or "\x00" in b.text:
                issues.append(
                    QualityIssue(
                        code="INVALID_ENCODING",
                        severity="blocking",
                        message=f"Block {b.block_id} contains replacement or null bytes",
                        page_number=b.source_span.page_number,
                    )
                )
        return issues

    def _check_duplicate_content(self, doc: CanonicalDocument) -> list[QualityIssue]:
        """Verify table cells are not leaked as duplicate paragraphs."""
        issues: list[QualityIssue] = []
        table_cell_texts: set[str] = set()
        for tbl in doc.tables:
            for r in tbl.rows:
                for c in r.cells:
                    val = c.raw_value.strip()
                    if len(val) >= 15:
                        table_cell_texts.add(val.lower())

        if not table_cell_texts:
            return issues

        duplicate_count = 0
        for b in doc.blocks:
            b_txt = b.text.lower().strip()
            if any(cell_txt in b_txt for cell_txt in table_cell_texts):
                duplicate_count += 1

        if duplicate_count > 5:
            issues.append(
                QualityIssue(
                    code="EXCESSIVE_DUPLICATE_CONTENT",
                    severity="warning",
                    message=f"Detected {duplicate_count} paragraphs repeating table content",
                )
            )
        return issues

    def _check_table_shape(self, doc: CanonicalDocument) -> list[QualityIssue]:
        """Ensure all rows match the expected column count."""
        issues: list[QualityIssue] = []
        for tbl in doc.tables:
            expected_cols = len(tbl.headers)
            if expected_cols == 0:
                continue
            for r in tbl.rows:
                if len(r.cells) != expected_cols and not r.is_continuation:
                    issues.append(
                        QualityIssue(
                            code="TABLE_ROW_COLUMN_MISMATCH",
                            severity="warning",
                            message=f"Row {r.row_id} has {len(r.cells)} cells, expected {expected_cols}",
                            table_id=tbl.table_id,
                            row_id=r.row_id,
                            page_number=r.source_pages[0] if r.source_pages else None,
                        )
                    )
                    break
        return issues

    def _check_table_headers(self, doc: CanonicalDocument) -> list[QualityIssue]:
        """Block publishing when a table has an unresolved or parser-generated header."""
        issues: list[QualityIssue] = []
        for tbl in doc.tables:
            invalid_headers = [
                header
                for header in tbl.headers
                if not header.strip() or re.fullmatch(r"Cột\s+\d+", header.strip(), re.IGNORECASE)
            ]
            if invalid_headers:
                issues.append(
                    QualityIssue(
                        code="UNRESOLVED_TABLE_HEADER",
                        severity="blocking",
                        message=(
                            f"Bảng '{tbl.table_id}' còn cột không xác định; cần tái dựng "
                            "cấu trúc hoặc hiệu đính trước khi lập chỉ mục."
                        ),
                        table_id=tbl.table_id,
                        page_number=tbl.source_pages[0] if tbl.source_pages else None,
                        raw_values=invalid_headers,
                    )
                )
        return issues

    def _check_duplicate_business_keys(self, doc: CanonicalDocument) -> list[QualityIssue]:
        """Block repeated program/task records that would create duplicate vectors."""
        issues: list[QualityIssue] = []
        seen_keys: dict[str, tuple[str, CanonicalTable, int]] = {}

        for tbl in doc.tables:
            headers_text = " ".join(tbl.headers).casefold()
            is_task_table = "nhiệm vụ" in headers_text and "đơn vị chủ trì" in headers_text
            is_admissions_program_table = (
                "tên ngành" in headers_text
                and ("phương thức" in headers_text or "tổ hợp" in headers_text)
            )
            for row in tbl.rows:
                values = [cell.raw_value.strip() for cell in row.cells]
                if not values:
                    continue
                business_key: str | None = None
                if is_task_table and re.fullmatch(r"\d+\.\d+", values[0]):
                    business_key = f"task:{values[0]}"
                elif (
                    is_admissions_program_table
                    and len(values) > 1
                    and re.fullmatch(r"\d{7}", values[1])
                ):
                    business_key = f"program:{values[1]}"
                if business_key is None:
                    continue

                row_signature = "\u241f".join(re.sub(r"\s+", " ", value).casefold() for value in values)
                previous = seen_keys.get(business_key)
                if previous is None:
                    seen_keys[business_key] = (row_signature, tbl, row.source_pages[0] if row.source_pages else 1)
                    continue

                previous_signature, previous_table, previous_page = previous
                if previous_signature == row_signature:
                    issues.append(
                        QualityIssue(
                            code="DUPLICATE_BUSINESS_RECORD",
                            severity="blocking",
                            message=(
                                f"Bản ghi '{business_key}' xuất hiện lặp trên trang "
                                f"{previous_page} và {row.source_pages[0] if row.source_pages else 1}."
                            ),
                            table_id=tbl.table_id,
                            row_id=row.row_id,
                            page_number=row.source_pages[0] if row.source_pages else None,
                            raw_values=[business_key, previous_table.table_id],
                        )
                    )
                else:
                    issues.append(
                        QualityIssue(
                            code="CONFLICTING_BUSINESS_RECORD",
                            severity="blocking",
                            message=(
                                f"Bản ghi '{business_key}' có dữ liệu khác nhau giữa "
                                f"các bảng '{previous_table.table_id}' và '{tbl.table_id}'."
                            ),
                            table_id=tbl.table_id,
                            row_id=row.row_id,
                            page_number=row.source_pages[0] if row.source_pages else None,
                            raw_values=[business_key],
                        )
                    )
        return issues

    def _check_cross_table_conflicts(self, doc: CanonicalDocument) -> list[QualityIssue]:
        """Detect conflicting business keys across different tables in the same document."""
        issues: list[QualityIssue] = []
        # Check admissions program codes for conflicts (e.g. AI: 7480107 vs 7480207)
        program_codes_by_name: dict[str, set[tuple[str, int]]] = {}

        for tbl in doc.tables:
            # Look for program code & name
            h_str = " ".join(tbl.headers).lower()
            if not ("ngành" in h_str):
                continue

            for r in tbl.rows:
                name = ""
                code = ""
                p_num = r.source_pages[0] if r.source_pages else 1
                for c in r.cells:
                    val = c.raw_value.strip()
                    if re.match(r"^\d{7}$", val):
                        code = val
                    elif "trí tuệ nhân tạo" in val.lower() or "công nghệ thông tin" in val.lower():
                        name = val

                if name and code:
                    clean_name = re.sub(r"\s+", " ", name.lower()).strip()
                    program_codes_by_name.setdefault(clean_name, set()).add((code, p_num))

        for name, code_entries in program_codes_by_name.items():
            unique_codes = {c for c, _ in code_entries}
            if len(unique_codes) > 1:
                issues.append(
                    QualityIssue(
                        code="CONFLICTING_PROGRAM_CODE",
                        severity="blocking",
                        message=(
                            f"Phát hiện mâu thuẫn mã ngành cho '{name}': "
                            f"{list(unique_codes)} trên các trang {sorted({p for _, p in code_entries})}"
                        ),
                        raw_values=sorted(unique_codes),
                    )
                )

        return issues
